"""
Risk Engine Orchestration Service (Phase 12 Hardening v1.1).
Provides high-level API to evaluate portfolio target compliance, execute deterministic risk
adjustments, and maintain audit records.
"""

from datetime import datetime, timezone
import logging
from typing import Dict, List, Optional, Union

from backend.app.config.settings import get_settings
from backend.app.portfolio.schemas import PortfolioTarget
from backend.app.risk.engine import RiskAdjustmentEngine
from backend.app.risk.schemas import (
    PortfolioCapitalContext,
    RiskAdjustedTarget,
    RiskAdjustmentRecord,
    RiskAssessment,
    RiskContext,
    RiskEngineConfig,
    RiskEngineRequest,
    RiskEngineResult,
    RiskStatus,
)
from backend.app.risk.storage import RiskStorage

logger = logging.getLogger(__name__)


class RiskEngineService:
    """
    High-level orchestrator for the Risk Engine subsystem.
    
    CRITICAL ARCHITECTURAL BOUNDARY:
    - Assesses portfolio targets generated by Phase 11.
    - Applies deterministic constraint enforcement and risk adjustment.
    - Does NOT execute trades, generate buy/sell orders, simulate P&L, or interface with brokers.
    """

    def __init__(
        self,
        config: Optional[RiskEngineConfig] = None,
        storage: Optional[RiskStorage] = None,
    ):
        self.config = config or self._build_config_from_settings()
        self.storage = storage or RiskStorage()

    @classmethod
    def _build_config_from_settings(cls) -> RiskEngineConfig:
        """Construct RiskEngineConfig from centralized settings."""
        settings = get_settings()
        return RiskEngineConfig(
            enabled=getattr(settings, "RISK_ENGINE_ENABLED", True),
            max_position_weight=getattr(settings, "RISK_MAX_POSITION_WEIGHT", 0.10),
            max_gross_exposure=getattr(settings, "RISK_MAX_GROSS_EXPOSURE", 1.00),
            max_net_exposure=getattr(settings, "RISK_MAX_NET_EXPOSURE", 1.00),
            max_long_exposure=getattr(settings, "RISK_MAX_LONG_EXPOSURE", 1.00),
            max_short_exposure=getattr(settings, "RISK_MAX_SHORT_EXPOSURE", 1.00),
            max_positions=getattr(settings, "RISK_MAX_POSITIONS", 20),
            max_leverage=getattr(settings, "RISK_MAX_LEVERAGE", 1.00),
            volatility_limit=getattr(settings, "RISK_VOLATILITY_LIMIT", None),
            correlation_limit=getattr(settings, "RISK_CORRELATION_LIMIT", None),
            turnover_limit=getattr(settings, "RISK_TURNOVER_LIMIT", None),
            max_daily_loss=getattr(settings, "RISK_MAX_DAILY_LOSS", None),
            max_drawdown=getattr(settings, "RISK_MAX_DRAWDOWN", None),
            adjustment_enabled=getattr(settings, "RISK_ADJUSTMENT_ENABLED", True),
            version=getattr(settings, "RISK_VERSION", "risk-v1.1"),
        )

    def assess(
        self,
        targets: Union[List[PortfolioTarget], RiskEngineRequest],
        context: Optional[RiskContext] = None,
        config: Optional[RiskEngineConfig] = None,
        timestamp: Optional[datetime] = None,
        save_artifact: bool = False,
    ) -> RiskEngineResult:
        """
        Evaluate portfolio targets against risk limits and return a RiskEngineResult.
        """
        # Unpack request if passed as RiskEngineRequest
        if isinstance(targets, RiskEngineRequest):
            req = targets
            target_list = req.targets
            context = req.context or context
            active_config = req.config or config or self.config
            eval_time = req.timestamp or timestamp or datetime.now(timezone.utc)
            req_meta = req.metadata
        else:
            target_list = targets
            active_config = config or self.config
            eval_time = timestamp or datetime.now(timezone.utc)
            req_meta = {}

        logger.info(
            f"Executing Risk Engine assessment at {eval_time.isoformat()} for {len(target_list)} targets"
        )

        # Execute deterministic risk adjustment / constraint enforcement
        (
            adjusted_targets,
            assessment,
            audit_trail,
            rejected_positions,
            was_adjusted,
            status,
        ) = RiskAdjustmentEngine.adjust(
            targets=target_list,
            config=active_config,
            context=context,
        )

        # Detect source construction version if available
        construction_ver = "portfolio-v1"
        if target_list and hasattr(target_list[0], "metadata"):
            construction_ver = target_list[0].metadata.get("construction_version", "portfolio-v1")

        result = RiskEngineResult(
            timestamp=eval_time,
            is_compliant=assessment.is_compliant,
            was_adjusted=was_adjusted,
            status=status,
            original_targets=target_list,
            adjusted_targets=adjusted_targets,
            assessment=assessment,
            audit_trail=audit_trail,
            rejected_positions=rejected_positions,
            capital=context.capital if (context and context.capital) else None,
            construction_version=construction_ver,
            risk_version=active_config.version,
            metadata={
                **req_meta,
                "adjustment_enabled": active_config.adjustment_enabled,
                "active_checks_count": len(assessment.checks),
                "violations_count": len(assessment.violations),
            },
        )

        if save_artifact:
            saved_path = self.storage.save_result(result)
            logger.info(f"Persisted risk assessment to {saved_path}")

        return result
